from _typeshed import Incomplete

P: Incomplete


class Deco:
    @staticmethod
    def black(text: str) -> str: ...
    @staticmethod
    def red(text: str) -> str: ...
    @staticmethod
    def green(text: str) -> str: ...
    @staticmethod
    def yellow(text: str) -> str: ...
    @staticmethod
    def blue(text: str) -> str: ...
    @staticmethod
    def magenta(text: str) -> str: ...
    @staticmethod
    def cyan(text: str) -> str: ...
    @staticmethod
    def white(text: str) -> str: ...
