
ESC: str


class Line:
    multi_line: "MultiLine"
    text: str
    def __init__(self, multi_line: "MultiLine", text: str = "") -> None: ...
    async def update(self, text: str) -> None: ...
    async def remove(self) -> None: ...


class MultiLine:
    lines: "Line"
    allow_remove_line: bool
    def __init__(self) -> None: ...
    def __del__(self) -> None: ...
    async def add_line(self, text: str = "") -> Line: ...
    async def update_line(self, text: str, line: Line) -> None: ...
    async def remove_line(self, line: Line) -> None: ...
