name: test

on:
  push

jobs:
  code_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
        
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install mypy

      - name: Do type checking (mypy)
        run: python -m mypy

      - name: Do testing (unittest)
        run: python3.11 -m unittest discover -s test
