name: Create Release

on:
  pull_request:
    types: [closed]
    branches:
      - release

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install build setuptools

      - name: Build package
        run: python -m build

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ github.event.pull_request.title }}
          tag_name: ${{ github.event.pull_request.title }}
          body: ${{ github.event.pull_request.body }}
          files: ./dist/*
          draft: false
          prerelease: false
